name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: कोड चेकआउट करें
        uses: actions/checkout@v4

      - name: जावा 17 सेटअप करें
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: फ्लटर सेटअप करें
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: एकदम नई फ्रेश पैकेज आईडी के साथ एंड्रॉयड बनाएं
        run: flutter create . --platforms=android --org com.shivai.app --project-name shiv_pro_editor

      - name: पैकेज डाउनलोड करें
        run: flutter pub get

      - name: मोबाइल के लिए फ्रेश एपीके बनाएं
        run: flutter build apk --debug

      - name: तैयार एपीके अपलोड करें
        uses: actions/upload-artifact@v4
        with:
          name: Shiv-Pro-Editor-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
          
